### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [Rudloff/openvegemap-cordova#1]
It would be pretty awesome to have this on F-Droid :)

**Comment by Rudloff** [comment]
Hello,
There is a request for this here: https://gitlab.com/fdroid/rfp/issues/145
Because F-Droid can't directly build Cordova projects, I first need to create a workflow to easily export the Android project in another repository.

**Comment by nicolasmaia** [comment]
Neat. Just to let you know, there is a demand for it :D

**Comment by nicolasmaia** [comment]
Awesome! Just downloaded it from F-Droid today :)
