### ISSUE TITLE
Add tooltip to map legend

### ISSUE THREAD

**Issue by nicolasmaia** [Rudloff/openvegemap-cordova#10]
It would be useful to see a tooltip upon mouseovering the legend, with helpful descriptions like "Places tagged with vegan=only on OpenStreetMap". 

Not really mission critical stuff, but it would make for a better experience.

**Comment by Rudloff** [comment]
Hello,
I don't want to explain it with OSM tags (some users might not know how OSM works) but I can do something like the tooltips in the filters window: https://github.com/Rudloff/openvegemap/blob/ae9f77337d9a60e285adbe02b795eee49c8baa0f/templates/filters.html#L5

**Comment by nicolasmaia** [comment]
Yep! That sounds great.

**Comment by Rudloff** [comment]
This will be in the next release (although only on desktop for now).
