### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by moshpirit** [Rudloff/openvegemap-cordova#11]
Hi! I made a quick logo, I'll probably create a few more when I have more time just in case you like it. 

![](https://i.imgur.com/sjWIdTX.png)

**Comment by Rudloff** [comment]
Hello,

Thanks for the offer!
I get the idea but I'm afraid it won't be very readable when used as a [favicon](https://www.w3.org/2005/10/howto-favicon):
![image](https://user-images.githubusercontent.com/840125/40580037-6be9101e-6136-11e8-933d-79338866e63f.png)
(OpenVegeMap is both an Android app and a web app so I would like to keep the same icon for both.)

**Comment by moshpirit** [comment]
Oh I didn't know. I'll work on that if you want when I have more time 😊

**Comment by 12people** [comment]
@moshpirit Since this is an Android app, too, it'd be nice to have a simpler icon that can be adapted for both circular and square icon variants. I'd suggest making an icon with just the pin and vegan symbols and all else removed.

**Comment by moshpirit** [comment]
Better now? 
I can also change the colours. 

![](https://i.imgur.com/x1VWJP0.png) 

[Album with all separated icons](https://imgur.com/a/mLfZuiq)

**Comment by Rudloff** [comment]
It's very nice! Thanks!

I really like the simple ones (without the cutlery). I think the cutlery is a nice idea to tell that the app is about food but I really like the simplicity of the first one.

I also like that you followed Material Design guidelines with shadows. Would it be possible to use the shadow of the bottom one but keep the fully white circle of the top one? It might be what would work the best at different sizes. What do you think?

Also, I see that a lot of Android apps now have a really small shadow around the background circle (see [here](https://f-droid.org/repo/icons-640/org.asteroidos.sync.11.png) or [here](https://f-droid.org/repo/com.simplemobiletools.notes/en-US/icon.png)). Do you think we should had something like this?

**Comment by moshpirit** [comment]
Sure!

![](https://i.imgur.com/GinRgJe.png)

This is a small version: 
![](https://i.imgur.com/ohUeir6.png)

And [here they are all of these separated](https://imgur.com/a/sk38SiY)

EDIT: I thought about giving some shadow in the opposite way to the white circle so it has a little of volume (but I'm not sure if you prefer it just flat): ![](https://i.imgur.com/TVbNpMd.png)

**Comment by Rudloff** [comment]
I really like the latest one.

Here is how it looks on my launcher:
![screenshot_20180529-113637](https://user-images.githubusercontent.com/840125/40651194-632dcc5c-6335-11e8-8bed-7361da11944c.png)
![screenshot_20180529-113645](https://user-images.githubusercontent.com/840125/40651195-634ab812-6335-11e8-908c-dc42114d18ee.png)

Thank you for all this work!

Under what license would you accept to publish this icon?
(OpenVegeMap is published under a [GPL license](https://github.com/Rudloff/openvegemap-cordova/blob/master/LICENSE) so the icon has to be under the same license or a compatible one.)

Also, would it be possible to export it as an SVG file? (So it is easier to adapt to new sizes.)

**Comment by moshpirit** [comment]
Hahaha awesome! Sure, GPL sounds great to me :) [Here's the SVG](https://my.owndrive.com/index.php/s/KKHts3nxOcLT9CF). Of course, feel free to change whatever you want ;)

**Comment by Rudloff** [comment]
I added the logo to the main repository: https://github.com/Rudloff/openvegemap/commit/645e65f1fd4c5c52d8c402b6f775584a8fcc1598
I will add it to the Android app in the next release.

Thanks again!

**Comment by moshpirit** [comment]
Thank you for this great app! :smile:
