### ISSUE TITLE
How is that Google doesn't track us?

### ISSUE THREAD

**Issue by moshpirit** [Rudloff/openvegemap-cordova#8]
First of all, thak you so much! It's the first app with OSM we can use online without downloading the maps. But it's also the first app I see it uses Google without a warning from F-droid.

**Comment by Rudloff** [comment]
Hello,
We don't use any Google API, the app just includes some links to Google Maps. So Google won't track you at all if you don't click those links (and you can select another routing provider in the preferences).

**Comment by moshpirit** [comment]
Awesome! Thank you!
